# Generated by Django 5.0 on 2023-12-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='featured_product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
